### ISSUE TITLE
QT waveform display needs a speedup 

### ISSUE THREAD

**Issue by MarkTitchener** [dbrnz/biosignalml-corelib#2]
The QT waveform browser might be made more responsive by limiting its initial display to the first ten minutes of a study... eg with http://polly.local/temporary/Traces_EDF

**Comment by dbrnz** [comment]
This is issue [#11](https://github.com/dbrnz/biosignalml-browser/issues/11) of the [BioSignalML Browser](https://github.com/dbrnz/biosignalml-browser).
